# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Setup
title:            Software Solved
tagline:          'A story about making it real'
description:      'What happens when an "architect" returns to his developer roots and tries to write propper software.'
url:              https://softwaresolved.github.io/blog
baseurl:          /

author:
  name:           'Phil Smith'
  url:            https://linkedin.com/in/philsmith

paginate:         3

# Custom vars
version:          0.0.1

github:
  repo:           https://github.com/softwaresolved/blog
