# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Setup
title:            Software Solved
tagline:          'A story about making it real'
description:      'A brazen two-column <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that pairs a prominent sidebar with uncomplicated content. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:              https://softwaresolved.github.io/blog
baseurl:          /

author:
  name:           'Phil Smith'
  url:            https://linkedin.com/in/philsmith

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/softwaresolved/blog
